server.port=8080
spring.application.name=be_hotel

spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=hotel_booking_system
spring.datasource.username=sa
spring.datasource.password=th15092004
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update