server.port=8080
spring.application.name=be_hotel
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=students;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
